# Title: 
#     Subclass is Reflexive
# Constraint Description: 
#     Any class is rdfs:subClassOf of itself.

#DRAFTING DO NOT USE

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?s ?o 
WHERE {
    ?s rdfs:subClassOf ?o .
    FILTER (?s != ?o) .
    
#Compare counts of subclasses with classes
}
